apiVersion: v1
kind: Namespace
metadata:
  name: dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: wil42/playground:1 # Remplacez "1" par "2" pour une nouvelle version
        ports:
        - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: dev
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer
